### ISSUE TITLE
Support Parallel Builds

### ISSUE THREAD

**Issue by eforest** [wokier/progress-maven-plugin#3]
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that are not marked as       *
[WARNING] * @threadSafe to support parallel building.                     *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe in XXX:
[WARNING] com.github.wokier.progress-maven-plugin:progress-maven-plugin:0.5

**Comment by wokier** [comment]
Fixed in 0.6
